name: "Lint documentation"

on:
  workflow_dispatch:
  push:
    branches: [ main, linux ]
  pull_request:
    branches: [ main, linux ]

jobs:
  lint-markdown:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: DavidAnson/markdownlint-cli2-action@d57f8bd57670b9c1deedf71219dd494614ff3335
        with:
          globs: "**/*.md"
